import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider1 from "./components/Provider1"
import ReduxProvider from "../app/components/ReduxProvider"
import SideBar from './components/SideBar'
import { useSession } from 'next-auth/react'
import { useEffect } from 'react'

import { useAppSelector, useAppDispatch } from "../app/hooks"
import { fetchUsers } from '@/features/user/userSlice'
import { Session } from 'inspector'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children

}: {
  children: React.ReactNode

}) {

  //

  return (
    <html lang="en">

      <ReduxProvider>

        <Provider1 >

          <body className={inter.className}>{children}</body>

        </Provider1>

      </ReduxProvider>


    </html>
  )
}
